name: Hostloc-auto

on:
  push:
    branches:
    - master
  schedule:
  - cron: 10 9 * * *

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run hostloc checkin
      env:
        hostloc_username: ${{ secrets.hostloc_username }}
        hostloc_password: ${{ secrets.hostloc_password }}
      run: |
        python run.py
